spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cheeup
    username: cheeup
    password: cheeup
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-second: 3600000 # 60*60 * 1000
  refresh-token:
    expiration-second: 86400000 # 60*60*24 * 1000

logging:
  level:
    org.springframework.security: debug

client:
  url: http://127.0.0.1:5500