INSERT INTO skills (name)
VALUES
    ('Java'),
    ('Python'),
    ('JavaScript'),
    ('TypeScript'),
    ('C++'),
    ('C#'),
    ('Ruby'),
    ('PHP'),
    ('Kotlin'),
    ('Rust'),
    ('Swift'),
    ('Objective-C'),
    ('R'),
    ('Dart'),
    ('Go'),
    ('Spring'),
    ('Django'),
    ('Flask'),
    ('NestJS'),
    ('Express.js'),
    ('React'),
    ('Vue.js'),
    ('Angular'),
    ('Svelte'),
    ('Next.js'),
    ('Nuxt.js'),
    ('Ruby on Rails'),
    ('Laravel'),
    ('Flutter'),
    ('Ionic'),
    ('React Native'),
    ('Xamarin'),
    ('Ktor'),
    ('TensorFlow'),
    ('PyTorch'),
    ('FastAPI'),
    ('OpenCV'),
    ('ROS'),
    ('FreeRTOS'),
    ('MySQL'),
    ('PostgreSQL'),
    ('SQL Server'),
    ('Oracle DB'),
    ('MongoDB'),
    ('Redis'),
    ('Cassandra'),
    ('Elasticsearch'),
    ('Neo4j'),
    ('Firebase'),
    ('Amazon S3'),
    ('Google Cloud Storage'),
    ('RESTful API'),
    ('GraphQL'),
    ('gRPC'),
    ('WebSocket'),
    ('JWT'),
    ('OAuth 2.0'),
    ('Firebase Authentication'),
    ('API Gateway'),
    ('AWS'),
    ('Google Cloud Platform'),
    ('Microsoft Azure'),
    ('IBM Cloud'),
    ('DigitalOcean'),
    ('Git'),
    ('SVN'),
    ('Jenkins'),
    ('GitLab CI'),
    ('GitHub Actions'),
    ('CircleCI'),
    ('Travis CI'),
    ('TeamCity'),
    ('Bamboo'),
    ('Ansible'),
    ('Chef'),
    ('Puppet'),
    ('SaltStack'),
    ('Docker'),
    ('Kubernetes'),
    ('OpenShift'),
    ('Docker Compose'),
    ('Helm'),
    ('Terraform'),
    ('CloudFormation'),
    ('Pulumi'),
    ('Prometheus'),
    ('Grafana'),
    ('ELK Stack'),
    ('Datadog'),
    ('New Relic'),
    ('Nagios'),
    ('Zabbix'),
    ('Splunk'),
    ('Fluentd'),
    ('Sentry'),
    ('Istio'),
    ('Linkerd'),
    ('Kong'),
    ('AWS API Gateway'),
    ('NGINX'),
    ('Consul'),
    ('Vault'),
    ('etcd'),
    ('Kubernetes ConfigMaps'),
    ('Memcached'),
    ('Varnish Cache'),
    ('RabbitMQ'),
    ('Apache Kafka'),
    ('Amazon SQS'),
    ('TensorFlow Lite'),
    ('OpenAI API'),
    ('Stable Baselines'),
    ('Figma'),
    ('Sketch'),
    ('Adobe XD'),
    ('InVision'),
    ('Zeplin'),
    ('Balsamiq'),
    ('Tailwind CSS'),
    ('Bootstrap'),
    ('Material UI'),
    ('Ant Design'),
    ('Chakra UI'),
    ('Styled-components'),
    ('Storybook'),
    ('GitHub'),
    ('GitLab'),
    ('Bitbucket'),
    ('Jira'),
    ('Trello'),
    ('Slack'),
    ('Arduino'),
    ('Raspberry Pi'),
    ('ESP32'),
    ('STM32'),
    ('Atmel AVR'),
    ('RTEMS'),
    ('LIDAR'),
    ('IMU'),
    ('Servo Motors'),
    ('Computer Vision'),
    ('Jest'),
    ('Mocha'),
    ('Cypress'),
    ('React Testing Library'),
    ('JUnit'),
    ('XCTest'),
    ('Espresso'),
    ('Selenium'),
    ('Postman'),
    ('HTML5'),
    ('CSS3');